import type { CieMathQuestion } from "./types";

const june2024 = {
  paper11: {
    questionPdf: {
      label: "June 2024 Question Paper 11",
      url: "https://www.cambridgeinternational.org/Images/567744-june-2024-question-paper-11.pdf",
    },
    markSchemePdf: {
      label: "June 2024 Mark Scheme Paper 11",
      url: "https://www.cambridgeinternational.org/Images/567738-june-2024-mark-scheme-paper-11.pdf",
    },
  },
  paper21: {
    questionPdf: {
      label: "June 2024 Question Paper 21",
      url: "https://www.cambridgeinternational.org/Images/567745-june-2024-question-paper-21.pdf",
    },
    markSchemePdf: {
      label: "June 2024 Mark Scheme Paper 21",
      url: "https://www.cambridgeinternational.org/Images/567739-june-2024-mark-scheme-paper-21.pdf",
    },
  },
  paper31: {
    questionPdf: {
      label: "June 2024 Question Paper 31",
      url: "https://www.cambridgeinternational.org/Images/567746-june-2024-question-paper-31.pdf",
    },
    markSchemePdf: {
      label: "June 2024 Mark Scheme Paper 31",
      url: "https://www.cambridgeinternational.org/Images/567740-june-2024-mark-scheme-paper-31.pdf",
    },
  },
  paper41: {
    questionPdf: {
      label: "June 2024 Question Paper 41",
      url: "https://www.cambridgeinternational.org/Images/673793-june-2024-question-paper-41.pdf",
    },
    markSchemePdf: {
      label: "June 2024 Mark Scheme Paper 41",
      url: "https://www.cambridgeinternational.org/Images/673787-june-2024-mark-scheme-paper-41.pdf",
    },
  },
  paper51: {
    questionPdf: {
      label: "June 2024 Question Paper 51",
      url: "https://www.cambridgeinternational.org/Images/673795-june-2024-question-paper-51.pdf",
    },
    markSchemePdf: {
      label: "June 2024 Mark Scheme Paper 51",
      url: "https://www.cambridgeinternational.org/Images/673789-june-2024-mark-scheme-paper-51.pdf",
    },
  },
  paper61: {
    questionPdf: {
      label: "June 2024 Question Paper 61",
      url: "https://www.cambridgeinternational.org/Images/673797-june-2024-question-paper-61.pdf",
    },
    markSchemePdf: {
      label: "June 2024 Mark Scheme Paper 61",
      url: "https://www.cambridgeinternational.org/Images/673791-june-2024-mark-scheme-paper-61.pdf",
    },
  },
};

const baseQuestion = {
  board: "CAIE",
  subjectName: "数学",
  syllabusCode: "9709",
  qualification: "AS/A Level",
  year: 2024,
  series: "May/June",
  variant: "1",
} satisfies Pick<
  CieMathQuestion,
  "board" | "subjectName" | "syllabusCode" | "qualification" | "year" | "series" | "variant"
>;

export const cieMathQuestionBank: CieMathQuestion[] = [
  {
    ...baseQuestion,
    id: "9709-2024-mj-11-q1",
    componentCode: "11",
    componentGroup: "pure",
    paperLabel: "Paper 1 Pure Mathematics 1",
    questionNumber: "1",
    title: "Completing the square and exact roots",
    topic: "Quadratics and algebra",
    questionSummary: "Rearrange an algebraic expression into completed-square form, then use it to solve an equation exactly.",
    answer: "完成平方式：(x − 3/2)² − 13/4；精确根 x = (3 ± √13) / 2。",
    markSchemeSummary: "Award method marks for the completed-square form, substitution, and exact radical solutions.",
    tags: ["quadratic", "complete square", "exact solution", "pure 1", "algebra"],
    ...june2024.paper11,
  },
  {
    ...baseQuestion,
    id: "9709-2024-mj-11-q2",
    componentCode: "11",
    componentGroup: "pure",
    paperLabel: "Paper 1 Pure Mathematics 1",
    questionNumber: "2",
    title: "Sine graph transformations",
    topic: "Trigonometric graphs",
    questionSummary: "Describe graph transformations from a sine curve and write the transformed function.",
    answer: "纵向拉伸 ×2 后向下平移 1 个单位，变换后函数 y = 2 sin x − 1。",
    markSchemeSummary: "Credit reflection, stretch/translation language, and a final function consistent with the transformed graph.",
    tags: ["trigonometry", "sin", "transformation", "graph", "pure 1"],
    ...june2024.paper11,
  },
  {
    ...baseQuestion,
    id: "9709-2024-mj-11-q3",
    componentCode: "11",
    componentGroup: "pure",
    paperLabel: "Paper 1 Pure Mathematics 1",
    questionNumber: "3",
    title: "Binomial expansion coefficient",
    topic: "Binomial expansion",
    questionSummary: "Use a given coefficient in an expansion to find a constant, then find a related coefficient.",
    answer: "常数 a = 2；所求项系数 = 240。",
    markSchemeSummary: "Marks come from applying the binomial coefficient formula and combining only the terms that produce the target power.",
    tags: ["binomial", "coefficient", "expansion", "pure 1"],
    ...june2024.paper11,
  },
  {
    ...baseQuestion,
    id: "9709-2024-mj-21-q1",
    componentCode: "21",
    componentGroup: "pure",
    paperLabel: "Paper 2 Pure Mathematics 2",
    questionNumber: "1",
    title: "Stationary point of a trigonometric curve",
    topic: "Differentiation",
    questionSummary: "Differentiate a trigonometric expression and solve for the stationary point in a restricted interval.",
    answer: "驻点坐标 (π/6, 3√3/2)，且为极大值点。",
    markSchemeSummary: "Method marks are tied to a correct derivative, setting it to zero, and giving the coordinate to the requested accuracy.",
    tags: ["differentiation", "stationary point", "trigonometry", "pure 2"],
    ...june2024.paper21,
  },
  {
    ...baseQuestion,
    id: "9709-2024-mj-21-q2",
    componentCode: "21",
    componentGroup: "pure",
    paperLabel: "Paper 2 Pure Mathematics 2",
    questionNumber: "2",
    title: "Implicit differentiation at a point",
    topic: "Implicit differentiation",
    questionSummary: "Find the gradient of a curve from an equation involving x, y, and logarithmic terms.",
    answer: "在给定点处梯度 dy/dx = −2。",
    markSchemeSummary: "Credit implicit differentiation, careful chain/product rules, substitution of the point, and simplification of the gradient.",
    tags: ["implicit differentiation", "gradient", "logarithm", "pure 2"],
    ...june2024.paper21,
  },
  {
    ...baseQuestion,
    id: "9709-2024-mj-21-q3",
    componentCode: "21",
    componentGroup: "pure",
    paperLabel: "Paper 2 Pure Mathematics 2",
    questionNumber: "3",
    title: "Graph-based inequality with exponentials",
    topic: "Inequalities and exponentials",
    questionSummary: "Sketch two graphs, use them to solve an inequality, then apply the result to an exponential expression.",
    answer: "解得 x < 1.43；满足条件的最大整数 n = 1。",
    markSchemeSummary: "Marks reward a usable sketch, correct interval reasoning, and substitution that identifies the largest valid integer.",
    tags: ["inequality", "exponential", "sketch", "pure 2"],
    ...june2024.paper21,
  },
  {
    ...baseQuestion,
    id: "9709-2024-mj-31-q1",
    componentCode: "31",
    componentGroup: "pure",
    paperLabel: "Paper 3 Pure Mathematics 3",
    questionNumber: "1",
    title: "Series expansion to a required power",
    topic: "Series expansion",
    questionSummary: "Expand a product of algebraic expressions in ascending powers and keep terms only up to a requested power.",
    answer: "展开到 x²：1 + 2x − 7x²。",
    markSchemeSummary: "Credit correct use of expansion rules, multiplying only relevant terms, and simplifying coefficients.",
    tags: ["pure 3", "series", "expansion", "ascending powers"],
    ...june2024.paper31,
  },
  {
    ...baseQuestion,
    id: "9709-2024-mj-31-q2",
    componentCode: "31",
    componentGroup: "pure",
    paperLabel: "Paper 3 Pure Mathematics 3",
    questionNumber: "2",
    title: "Logarithmic equation solved numerically",
    topic: "Logarithms",
    questionSummary: "Solve a logarithmic equation and give the numerical answer to the requested accuracy.",
    answer: "x = 1.71（保留 3 位有效数字）。",
    markSchemeSummary: "Marks reward valid logarithmic manipulation or numerical solving, plus a final value rounded correctly.",
    tags: ["pure 3", "logarithm", "equation", "numerical solution"],
    ...june2024.paper31,
  },
  {
    ...baseQuestion,
    id: "9709-2024-mj-31-q4",
    componentCode: "31",
    componentGroup: "pure",
    paperLabel: "Paper 3 Pure Mathematics 3",
    questionNumber: "4",
    title: "Complex numbers in polar form",
    topic: "Complex numbers",
    questionSummary: "Convert a complex number into polar form, then combine complex numbers and express the result in modulus-argument form.",
    answer: "z = 2(cos π/3 + i sin π/3)；乘积 = 4 cis(2π/3)。",
    markSchemeSummary: "Credit exact modulus and argument work, correct use of polar multiplication/division, and the final angle range.",
    tags: ["pure 3", "complex numbers", "polar form", "modulus", "argument"],
    ...june2024.paper31,
  },
  {
    ...baseQuestion,
    id: "9709-2024-mj-41-q1",
    componentCode: "41",
    componentGroup: "mechanics",
    paperLabel: "Paper 4 Mechanics",
    questionNumber: "1",
    title: "Velocity-time graph and distance",
    topic: "Kinematics",
    questionSummary: "Sketch a velocity-time graph for staged motion and calculate the total distance from areas under the graph.",
    answer: "由图形面积求得总位移 = 540 m。",
    markSchemeSummary: "Credit correct graph sections and area calculations for acceleration, constant-speed, and deceleration intervals.",
    tags: ["mechanics", "kinematics", "velocity time graph", "distance"],
    ...june2024.paper41,
  },
  {
    ...baseQuestion,
    id: "9709-2024-mj-41-q2",
    componentCode: "41",
    componentGroup: "mechanics",
    paperLabel: "Paper 4 Mechanics",
    questionNumber: "2",
    title: "Resultant force components",
    topic: "Forces",
    questionSummary: "Resolve forces into components, apply a zero-component condition, then calculate a resultant magnitude and direction.",
    answer: "合力大小 ≈ 14.2 N，方向与水平约成 38°。",
    markSchemeSummary: "Marks are awarded for correct component equations, vector addition, magnitude, and direction.",
    tags: ["mechanics", "forces", "components", "resultant"],
    ...june2024.paper41,
  },
  {
    ...baseQuestion,
    id: "9709-2024-mj-51-q1",
    componentCode: "51",
    componentGroup: "statistics",
    paperLabel: "Paper 5 Probability & Statistics 1",
    questionNumber: "1",
    title: "Combined mean and standard deviation",
    topic: "Data summaries",
    questionSummary: "Combine two sets of summary statistics to find the overall mean and standard deviation.",
    answer: "合并后均值 = 24.5，标准差 ≈ 6.32。",
    markSchemeSummary: "Marks reward combining totals correctly, using the variance formula consistently, and square-rooting for standard deviation.",
    tags: ["statistics 1", "mean", "standard deviation", "summary statistics"],
    ...june2024.paper51,
  },
  {
    ...baseQuestion,
    id: "9709-2024-mj-51-q3",
    componentCode: "51",
    componentGroup: "statistics",
    paperLabel: "Paper 5 Probability & Statistics 1",
    questionNumber: "3",
    title: "Histogram and interquartile range",
    topic: "Grouped data",
    questionSummary: "Use grouped frequency data to draw a histogram and reason about an upper bound for the interquartile range.",
    answer: "频率密度依次 0.4 / 0.9 / 1.2…；四分位距上界 IQR ≤ 18。",
    markSchemeSummary: "Credit frequency density setup, accurate histogram bars, and valid quartile reasoning from cumulative frequencies.",
    tags: ["statistics 1", "histogram", "grouped data", "interquartile range"],
    ...june2024.paper51,
  },
  {
    ...baseQuestion,
    id: "9709-2024-mj-51-q5",
    componentCode: "51",
    componentGroup: "statistics",
    paperLabel: "Paper 5 Probability & Statistics 1",
    questionNumber: "5",
    title: "Binomial probability and approximation",
    topic: "Binomial distribution",
    questionSummary: "Find binomial probabilities over repeated days and use a suitable approximation for a larger number of trials.",
    answer: "二项概率 P = 0.184；正态近似 P ≈ 0.212。",
    markSchemeSummary: "Marks cover binomial tail probabilities, complement reasoning, approximation choice, and continuity correction where needed.",
    tags: ["statistics 1", "binomial", "normal approximation", "probability"],
    ...june2024.paper51,
  },
  {
    ...baseQuestion,
    id: "9709-2024-mj-61-q1",
    componentCode: "61",
    componentGroup: "statistics",
    paperLabel: "Paper 6 Probability & Statistics 2",
    questionNumber: "1",
    title: "Combined Poisson model",
    topic: "Poisson distribution",
    questionSummary: "Combine independent Poisson rates over a changed time interval and find a tail probability.",
    answer: "合并速率 λ = 4.5；P(X > 2) = 0.826。",
    markSchemeSummary: "Credit combining means, scaling for the time period, and using the complement or direct cumulative probability correctly.",
    tags: ["statistics 2", "poisson", "independent", "probability"],
    ...june2024.paper61,
  },
  {
    ...baseQuestion,
    id: "9709-2024-mj-61-q3",
    componentCode: "61",
    componentGroup: "statistics",
    paperLabel: "Paper 6 Probability & Statistics 2",
    questionNumber: "3",
    title: "Confidence interval interpretation",
    topic: "Confidence intervals",
    questionSummary: "Calculate a confidence interval, judge an interpretation, and reason about two independent intervals.",
    answer: "95% 置信区间 ≈ (48.6, 53.4)；该区间描述长期覆盖比例，而非单次概率。",
    markSchemeSummary: "Marks cover the interval formula, the meaning of confidence level, and conditional probability for interval coverage.",
    tags: ["statistics 2", "confidence interval", "normal", "conditional probability"],
    ...june2024.paper61,
  },
];
